blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDetailView, BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView, toggle_published, \
    BlogAllListView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('published/<int:pk>/', toggle_published, name='toggle_published'),
    path('all/', BlogAllListView.as_view(), name='blog_all_list'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='превью', **NULLABLE)
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='дата создания', **NULLABLE)
    date_modified = models.DateTimeField(auto_now=True, verbose_name='последнее изменение', **NULLABLE)
    publication_sign = models.TextField(verbose_name='признак публикации')
    view_count = models.IntegerField(default=0, verbose_name='просмотры')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from blog.models import Blog


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogAllListView(ListView):
    model = Blog

    template_name = 'blog/blog_all_list.html'


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogCreateView(CreateView):
    model = Blog
    extra_context = {
        'title': 'Создание статьи',
    }
    fields = ['title', 'body', 'preview', 'is_published']
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    extra_context = {
        'title': 'Редактирование статьи',
    }
    fields = ['title', 'body', 'preview', 'is_published']

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')


def toggle_published(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.is_published:
        blog_item.is_published = False
    else:
        blog_item.is_published = True

    blog_item.save()

    return redirect(reverse('blog:blog_list'))

blog/templates/blog/blog_all_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Статьи</h1>
</div>
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Создать статью</a>
       <a class="btn btn-outline-primary" href="{% url 'blog:blog_list' %}">Опубликованные</a> <!-- #переход на нефильтрованную страницу-->
    </div>
    {% for object in object_list %}
        <div class="col-4 mb-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">
                        {{ object|title }}
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blog:blog_detail' object.pk %}"
                               class="btn btn-sm btn-outline-secondary">View</a>
                            <a href="{% url 'blog:blog_edit' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Edit</a>
                            <a href="{% url 'blog:blog_delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-secondary">Delete</a>
                        </div>
                        {% if object.is_published %}
                        <a class="text-danger" href="{% url 'blog:toggle_published' object.pk %}">Снять с публикации</a>
                        {% else %}
                         <a class="text-primary" href="{% url 'blog:toggle_published' object.pk %}">Опубликовать</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p>Удалить статью "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                             <a href="{% url 'blog:blog_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">
    <div class="card mb-3" style="max-width: 100%; ">
        <div class="row g-0">
            <div class="col-md-4 w-100 p-3">
                {% if object.preview %}
                <img src="{% my_media object.preview %}" class="img-fluid rounded float-start" alt="{{ object.name }}">
                {% else %}
                <img src="/media/Unknown.jpeg" class="rounded float-start" style="width: 250; height: 250;  "
                     alt="unknown">
                {% endif %}
            </div>
            <div class="col-md-8" style="width: 100%; height: 100%;">
                <div class="card-body">
                    <div class="card-header">
                        <h5 class="card-title">{{ object.title }} ({{ object.slug }})</h5>
                        <h8> ==================== </h8>
                        <p class="card-text">{{ object.body }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-12">
    <div class="card-footer" style="max-width: 100%;">
        <br>
        <p>Количество просмотров: {{ object.view_count }}</p>
        <p class="card-text"><small class="text-body-secondary">Создано: {{ object.date_of_creation}}</small></p>
        <p class="card-text"><small class="text-body-secondary">Обновлено: {{ object.date_modified }}</small></p>

    </div>

</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать</button>
                                {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Статьи</h1>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Создать статью</a>
    <a class="btn btn-outline-primary" href="{% url 'blog:blog_all_list' %}">Все статьи</a>
    <!-- #переход на нефильтрованную страницу-->
</div>
{% for object in object_list %}
<div class="col-4 mb-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {{ object|title }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'blog:blog_detail' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">View</a>
                    <a href="{% url 'blog:blog_edit' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Edit</a>
                    <a href="{% url 'blog:blog_delete' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Delete</a>
                </div>
                {% if object.is_published %}
                <a class="text-danger" href="{% url 'blog:toggle_published' object.pk %}">Снять с публикации</a>
                {% else %}
                <a class="text-primary" href="{% url 'blog:toggle_published' object.pk %}">Опубликовать</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}