blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDetailView, BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView, toggle_published, \
    BlogAllListView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('published/<int:pk>/', toggle_published, name='toggle_published'),
    path('all/', BlogAllListView.as_view(), name='blog_all_list'),

]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_item'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    preview = models.ImageField(upload_to='product/', verbose_name='превью', **NULLABLE)
    category = models.ForeignKey('catalog.Category', on_delete=models.PROTECT, verbose_name='категория', **NULLABLE)
    price = models.PositiveIntegerField(verbose_name='цена')
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='дата создания', **NULLABLE)
    last_modified_date = models.DateTimeField(auto_now_add=True, verbose_name='последнее изменение', **NULLABLE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='пользователь')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number = models.FloatField(verbose_name='номер версии')
    name = models.CharField(max_length=150, verbose_name='название версии')
    is_active = models.BooleanField(default=False, verbose_name='активная')

    def __str__(self):
        return f'{self.name}({self.number})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin():
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('date_of_creation', 'last_modified_date', 'user',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        list_word = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар', ]

        for word in list_word:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Это запрещенный продукт, нельзя добавить!')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        list_word = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар', ]

        for word in list_word:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Это запрещенный продукт, нельзя добавить!')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}) : {message}')
    context = {
        'title': 'Контакты'
    }
    return render(request, 'catalog/contacts.html', context)


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        for product in context_data['object_list']:
            product.active_version = product.version_set.filter(is_active=True).first()

        return context_data


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product_item.html'
    login_url = reverse_lazy('users:login')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        product = self.object  # Получаем объект продукта из представления

        product.active_version = product.version_set.filter(is_active=True).first()

        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.instance.user = self.request.user
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    login_url = reverse_lazy('users:login')

    def get_success_url(self):
        return reverse('catalog:update_product', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

catalog/templates/catalog/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/album.css" rel="stylesheet">
</head>
<body>

{% include 'catalog/includes/inc_catalog_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{title}}</h1>
</div>

<div class="container">
    <div class="row text-center">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy;{% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
<script src="/static/js/popper.min.js"></script>
<script src="/static/js/holder.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-lg-9 col-md-6 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <table class="table table-striped">
                <tr>
                    <td class="w-25">Страна</td>
                    <td>USA</td>
                </tr>
                <tr>
                    <td class="w-25">ИНН</td>
                    <td>91-1144442</td>
                </tr>
                <tr>
                    <td class="w-25">Адрес</td>
                    <td>Redmond,WA,98052-6399</td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="col-lg-3 col-md-6 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
        </div>
        <div class="card-body">
            <form method="post" action="" class="form-floating">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="name">Имя</label>
                    <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                </div>
                <div class="mb-3">
                    <label for="phone">Телефон</label>
                    <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                           required>
                </div>
                <div class="mb-3">
                    <label for="message">Сообщение</label>
                    <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение"
                              required></textarea>
                </div>
            </form>
            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Каталог</h1>
</div>

<div class="col-12 mb-5">
    <a class="btn btn-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
</div>

{% for object in object_list %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">
                {{object|title}}
            </h4>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{object.description|title}}</li> <br>
                <li>Добавил продукт: {{object.user|default:'-'}}</li>
            </ul>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                {% if object.active_version %}
                    Активная версия: {{ object.active_version.name }}
                    ({{ object.active_version.number }})
                {% else %}
                    Нет активной версии
                {% endif %}
            </ul>
            <div class="btn-group">
                <a class="btn btn-sm btn-outline-primary" href="{% url 'catalog:product_item' object.pk %}"
                   role="button">Перейти к товару</a>
                <a href="{% url 'catalog:update_product' object.pk %}" type="button"
                   class="btn btn-sm btn-outline-success">Изменить</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <h4> Добавление продукта</h4>
                        </div>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                            <a href="{% url 'catalog:home'%}" type="button"
                               class="btn btn-sm btn-outline-success">Назад</a>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <h4> Версия продукта</h4>
                        </div>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                                <hr>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_item.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">
    <div class="card mb-3" style="max-width: 100%; ">
        <div class="row g-0">
            <div class="col-md-4 w-100 p-3">
                <div class="card-header">
                    <h5 class="card-title">{{object|title}}</h5>
                </div>
                {% if object.preview %}
                <img src="{% my_media object.preview %}" class="img-fluid rounded float-start" alt="{{ object.name }}">
                {% else %}
                <img src="/media/Unknown.jpeg" class="rounded float-start" style="width: 250; height: 250;  "
                     alt="unknown">
                {% endif %}
            </div>
            <div class="col-md-8" style="width: 100%; height: 100%;">
                <div class="card-body">
                    <div class="card-footer">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <p class="card-text">Категория: {{ object.category }}</p>
                            <li>Описание: {{object.description|title}}</li>
                            <br>
                            <li class="card-title pricing-card-title"> Цена: {{object.price|title}} руб.</li>
                            <li class="card-footer">
                                <li>Добавил продукт: {{object.user|default:'-'}}</li> <br>
                                {% if object.active_version %}
                                Активная версия: {{ object.active_version.name }}
                                ({{ object.active_version.number }})
                                {% else %}
                                Нет активной версии
                                {% endif %}
                            </li>
                        </ul>

                        <button type="button" class="btn btn-lg btn-outline-primary">Купить</button>
                        <a href="{% url 'catalog:update_product' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-success">Изменить</a>
                        <a href="{% url 'catalog:home' %}" type="button"
                           class="btn btn-sm btn-outline-success">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}